In [ ]:
#importing libraries
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [ ]:
data = pd.read_json("preprocessed_data.jsonl",lines=True)
data.sample(10)
#we are going to work on arabic (src)
data = data[['src',"label"]].rename(columns={'src':'text'})
data

                                                    text label
0                                     وي انا تعجبني برشا   pos
1                                         تبارك اله عليه   pos
2          امرأة أنيقة و سلسة في خطابها و ذكية و متواضعة   pos
3      جعفر يحب بلادو ويعمل في الخير يعاون في الناس و...   pos
4                                                 محلاها   pos
...                                                  ...   ...
17049                          شبعة خمج.اينما يقيم الجهل   neg
17050  الانسان هذا مافهمتش شنوه دينو وشنوه انتماءاتو ...   neg
17051             عار عليكم اليوم تجيبوا هالمناظر لتلفزة   neg
17052            ما اخيبها سهرية خاطر انتي فيها يا مقداد   neg
17053     عدم إحترام المشاهد من جميع الأطراف هي قلة حياء   neg

[17054 rows x 2 columns]

In [ ]:
data['label'] = data['label'].apply(lambda x: 1 if x == 'pos' else 0)
#remove dots :

data['text'] = data['text'].str.replace('.', '')
data.sample(10)

                                                    text  label
3379   برافو برافو برافو برافو برافو برافو برافو براف...      1
14903                          واله خير من نوفل الورتاني      1
2657            لطفي يعطيك الصحة شرفت تونس وحدك الحاصيلو      1
7911                                           قانة كفرة      0
8650                                      تافه تفوه عليك      0
12139                    قلت حياء أما ثلث من الواقع لاسف      0
15736               نهار كامل و هوى يتسردك علينا هذا -_-      0
1427                      فرامون سيتكوم روعة ضحك بالدموع      1
14801                                          معلم سامي      1
13926                                  برافو خالد شوكات       1

In [ ]:
#printing the number of training and testing positive and negative text
train_data = data.sample(frac=0.8, random_state=42)
test_data = data.drop(train_data.index)

pos_train_text = train_data[train_data['label'] == 1]['text'].tolist()
neg_train_text = train_data[train_data['label'] == 0]['text'].tolist()

print("Number of training positive text: ", len(pos_train_text))
print("Number of training negative text: ", len(neg_train_text))

Number of training positive text:  7108
Number of training negative text:  6535

In [ ]:
#tokinize by space
def tokenize(text):
    return text.split()

data['tokinized_text'] = data['text'].apply(tokenize)
data.sample(100)

,text,label,tokinized_text
13489,ماسط,0,[ماسط]
16300,جبالك الرواسي و لا المنظر هذا,0,"[جبالك, الرواسي, و, لا, المنظر, هذا]"
15572,ماسط,0,[ماسط]
7556,طيح سعدك حنان,0,"[طيح, سعدك, حنان]"
2086,وحدك في الوهرة يا أمين قارة,1,"[وحدك, في, الوهرة, يا, أمين, قارة]"
...,...,...,...
8426,تفوه على اولاد الكلبة,0,"[تفوه, على, اولاد, الكلبة]"
7086,انت معلم يسكتو وأنت موجود ميقدرو يتكلمو وله معلم,1,"[انت, معلم, يسكتو, وأنت, موجود, ميقدرو, يتكلمو..."
4056,يا خويا يعجبني,1,"[يا, خويا, يعجبني]"
5435,يقتل,1,[يقتل]
15239,نضالتحدي و أمل بصراحة أكثر من رائعة سيدتي,1,"[نضالتحدي, و, أمل, بصراحة, أكثر, من, رائعة, سي..."

In [ ]:
#stemming
from nltk.stem.isri import ISRIStemmer
stemmer = ISRIStemmer()
def stem_words(words):
    return [stemmer.stem(word) for word in words]

data['stemmed_text'] = data['tokinized_text'].apply(stem_words)
data.sample(10)

#the arabic stemmer doesn't work very well on tunisian arabic so im going to train two models one for the tokinized text and another for the stemmed text

,text,label,tokinized_text,stemmed_text
15371,تفو عليكم تعلموا في بناتكم الرخس وقلة التربية ...,0,"[تفو, عليكم, تعلموا, في, بناتكم, الرخس, وقلة, ...","[تفو, علي, علم, في, بنت, رخس, وقل, ربي, رملم, ..."
2102,كافون يا معلم ديما محفلها و عاملنا جو برافو,1,"[كافون, يا, معلم, ديما, محفلها, و, عاملنا, جو,...","[كاف, يا, علم, ديم, حفل, و, عمل, جو, رفو]"
14480,ما نبالغشكنقول تونس كاملة تحبها كمثلة ناجحة وم...,1,"[ما, نبالغشكنقول, تونس, كاملة, تحبها, كمثلة, ن...","[ما, نبالغشكنقول, ونس, كمل, تحب, كمثل, نجح, وم..."
6495,بصراحة نور شيبا برافو,1,"[بصراحة, نور, شيبا, برافو]","[صرح, نور, شيب, رفو]"
7974,وجيهة انحشى على عصبها شوية وسع بالك يا وجيهة,0,"[وجيهة, انحشى, على, عصبها, شوية, وسع, بالك, يا...","[وجه, حشى, على, عصب, شوة, وسع, بلك, يا, وجه]"
6096,جعفور المعلم و راجل,1,"[جعفور, المعلم, و, راجل]","[جعفور, علم, و, رجل]"
2339,معلم و حافظوا عليه,1,"[معلم, و, حافظوا, عليه]","[علم, و, حفظ, عليه]"
10372,ساقطة إيناس,0,"[ساقطة, إيناس]","[سقط, ينس]"
16304,حسيت روحي بهمت,0,"[حسيت, روحي, بهمت]","[حست, روح, بهم]"
13996,محبوب وباهي وتستاهل كل خير,1,"[محبوب, وباهي, وتستاهل, كل, خير]","[حبب, وبه, تهل, كل, خير]"

In [ ]:
#printing the number of training and testing positive and negative text
train_data = data.sample(frac=0.8, random_state=42)
test_data = data.drop(train_data.index)

pos_train_text = train_data[train_data['label'] == 1]['text'].tolist()
neg_train_text = train_data[train_data['label'] == 0]['text'].tolist()

print("Number of training positive text: ", len(pos_train_text))
print("Number of training negative text: ", len(neg_train_text))


pos_train_corpus = " ".join(pos_train_text)
neg_train_corpus = " ".join(neg_train_text)

Number of training positive text:  7108
Number of training negative text:  6535

In [ ]:
#building the vocabulary from the tokinized
corpus = " ".join(data["text"] )
vocab_tokinized = set(corpus.split())
vocab_size_tokinized = len(vocab_tokinized)
print("Vocabulary size: ", vocab_size_tokinized)

#building the vocbulary from the stemmed

vocab_stemmed = set(
    w
    for _, row in data.iterrows()
    for w in row["stemmed_text"])




vocab_size_stemmed = len(vocab_stemmed)
print("Vocabulary size: ", vocab_size_stemmed)

Vocabulary size:  20354
Vocabulary size:  8218

In [ ]:
#let's start with tokenized model
#frequency dict
freq = dict()
for w in vocab_tokinized:
  positive_occ = pos_train_corpus.count(w)
  negative_occ = neg_train_corpus.count(w)
  freq[w] = (positive_occ,negative_occ)

In [ ]:
def word2freq(w:str):
  return freq.get(w,(0,0))

In [ ]:
for w in vocab_tokinized:
  pos,neg = word2freq(w)
  print(f"word : {w}  pos : {pos}  neg : {neg} ")

word : وضع  pos : 2  neg : 8
word : مالثورة  pos : 0  neg : 1
word : نعلة  pos : 0  neg : 7
word : 10000  pos : 3  neg : 0
word : تقن  pos : 3  neg : 5
word : المتربين  pos : 0  neg : 1
word : يعارض  pos : 1  neg : 0
word : عالريمة  pos : 1  neg : 0
word : ابهيم  pos : 0  neg : 6
word : ملامهزلةه  pos : 0  neg : 1
word : -)  pos : 57  neg : 2
word : فوري  pos : 0  neg : 0
word : نزيدو  pos : 0  neg : 2
word : الحمراوي  pos : 2  neg : 0
word : يسكت  pos : 2  neg : 2
word : 10000000000000000000000  pos : 1  neg : 0
word : نعتزل  pos : 1  neg : 0
word : الحسد  pos : 3  neg : 1
word : والتفاهة  pos : 0  neg : 3
word : الخفاش  pos : 0  neg : 1
word : نرحموك  pos : 0  neg : 1
word : التوت  pos : 0  neg : 1
word : وفن  pos : 4  neg : 0
word : تجريح  pos : 1  neg : 1
word : همني  pos : 0  neg : 1
word : معاش  pos : 1  neg : 5
word : حيو  pos : 1  neg : 75
word : لأنذال  pos : 0  neg : 0
word : معمري  pos : 0  neg : 0
word : تبندير  pos : 1  neg : 5
word : الميثالي  pos : 1  neg : 0
word : صفاقس  pos : 6  neg : 7
word : مكلينك  pos : 0  neg : 1
word : إسلامية  pos : 0  neg : 5
word : المال  pos : 2  neg : 2
word : وكأنك  pos : 1  neg : 0
word : بنتي  pos : 6  neg : 6
word : فعلنا  pos : 0  neg : 1
word : ايطول  pos : 1  neg : 0
word : الناي  pos : 1  neg : 0
word : كاريزماقداش  pos : 1  neg : 0
word : ياقو  pos : 1  neg : 0
word : دكتور  pos : 0  neg : 2
word : عينو  pos : 17  neg : 1
word : حويتة  pos : 1  neg : 0
word : الجزاير  pos : 2  neg : 7
word : العميري  pos : 1  neg : 0
word : نفسو  pos : 0  neg : 1
word : بالسياسة  pos : 1  neg : 0
word : عطية  pos : 1  neg : 0
word : تب  pos : 296  neg : 113
word : ميعرش  pos : 0  neg : 1
word : مزبلة  pos : 0  neg : 3
word : قرايتك  pos : 0  neg : 0
word : معبودتي  pos : 0  neg : 0
word : شرقية  pos : 2  neg : 0
word : بالميبون  pos : 0  neg : 1
word : الهابطه  pos : 0  neg : 1
word : الرذالة  pos : 1  neg : 1
word : شادت  pos : 0  neg : 1
word : عطاها  pos : 1  neg : 0
word : الحقيقية  pos : 3  neg : 1
word : امرءة  pos : 1  neg : 0
word : قدامو  pos : 0  neg : 3
word : سكين  pos : 5  neg : 59
word : كوميك  pos : 0  neg : 2
word : النقبة  pos : 0  neg : 2
word : مطالبه  pos : 0  neg : 1
word : يجرى  pos : 0  neg : 1
word : الصياح  pos : 1  neg : 1
word : قطعي  pos : 0  neg : 2
word : تجودير  pos : 0  neg : 1
word : ياع  pos : 3  neg : 10
word : تاويلي  pos : 1  neg : 0
word : انتانسان  pos : 0  neg : 0
word : أبار  pos : 0  neg : 1
word : طول  pos : 15  neg : 20
word : وشلاكة  pos : 0  neg : 2
word : افهموا  pos : 0  neg : 0
word : عبرة  pos : 1  neg : 1
word : لحيتك  pos : 0  neg : 1
word : التلفزات  pos : 0  neg : 2
word : يدعون  pos : 0  neg : 0
word : سعده  pos : 1  neg : 3
word : برواح  pos : 2  neg : 0
word : لباجى  pos : 0  neg : 1
word : حافظوا  pos : 1  neg : 0
word : دولسي  pos : 1  neg : 0
word : هل  pos : 36  neg : 192
word : فسادا  pos : 0  neg : 2
word : تقوم  pos : 2  neg : 3
word : لذا  pos : 1  neg : 3
word : ماخمجكموالهاتفوهاعليكم  pos : 0  neg : 1
word : السبيلالهم  pos : 0  neg : 1
word : بتاع  pos : 0  neg : 1
word : التبندير  pos : 0  neg : 5
word : خايبه  pos : 0  neg : 1
word : ماسط  pos : 9  neg : 1421
word : هذى  pos : 0  neg : 2
word : خادمة  pos : 1  neg : 0
word : 5  pos : 2  neg : 5
word : تلفتلكش  pos : 1  neg : 0
word : ماسخو  pos : 0  neg : 2
word : لماكياج  pos : 1  neg : 0
word : بلفط  pos : 0  neg : 1
word : فيالبلاد  pos : 0  neg : 1
word : نبارة  pos : 7  neg : 1
word : بمنصف  pos : 0  neg : 1
word : هالخوات  pos : 2  neg : 0
word : "اله  pos : 0  neg : 1
word : والنتيجة  pos : 1  neg : 0
word : والرذيله  pos : 0  neg : 1
word : يجيكم  pos : 0  neg : 1
word : العصا  pos : 1  neg : 1
word : عملت  pos : 8  neg : 72
word : الاجيال  pos : 0  neg : 1
word : ومتخلف  pos : 0  neg : 2
word : والمساجد  pos : 0  neg : 1
word : حبو  pos : 120  neg : 51
word : نحبها  pos : 122  neg : 3
word : سكان  pos : 0  neg : 2
word : هاته  pos : 4  neg : 2
word : ختمت  pos : 0  neg : 1
word : تقبل  pos : 19  neg : 8
word : ومنافقاتعقلي  pos : 0  neg : 1
word : حاميكي  pos : 0  neg : 1
word : لميدان  pos : 3  neg : 0
word : زهرها  pos : 0  neg : 1
word : أقنعتو  pos : 0  neg : 1
word : الرد  pos : 0  neg : 16
word : ساحة  pos : 3  neg : 6
word : سحتوه  pos : 0  neg : 1
word : بسراحة  pos : 0  neg : 1
word : ياديوث  pos : 0  neg : 0
word : سخسخوكم  pos : 0  neg : 0
word : اجمعين  pos : 2  neg : 0
word : حنونة  pos : 8  neg : 0
word : براڤوا  pos : 0  neg : 0
word : مالطول  pos : 0  neg : 1
word : شلا  pos : 5  neg : 95
word : بار  pos : 322  neg : 69
word : طيح  pos : 9  neg : 34
word : متحكمها  pos : 0  neg : 1
word : مستمرة  pos : 0  neg : 1
word : انعذبوهم  pos : 0  neg : 0
word : رجلإحترامتي  pos : 0  neg : 0
word : ندعى  pos : 0  neg : 1
word : ثفافة  pos : 0  neg : 0
word : تجوك  pos : 1  neg : 0
word : نرا  pos : 7  neg : 8
word : سومبلمون  pos : 0  neg : 0
word : الفائزة  pos : 1  neg : 0
word : الأرض  pos : 0  neg : 6
word : ظالو  pos : 0  neg : 1
word : عملك  pos : 2  neg : 5
word : اباحية  pos : 0  neg : 1
word : ماسطتها  pos : 0  neg : 1
word : العفسة  pos : 1  neg : 0
word : ياكلكم  pos : 0  neg : 0
word : بعفويا  pos : 1  neg : 0
word : غناية  pos : 2  neg : 7
word : يكسرلي  pos : 0  neg : 1
word : قنك  pos : 0  neg : 1
word : صدورها  pos : 0  neg : 1
word : وتجيبوه  pos : 0  neg : 1
word : الماركات  pos : 0  neg : 1
word : جبتها  pos : 1  neg : 2
word : بري  pos : 14  neg : 54
word : ازلام  pos : 0  neg : 1
word : خلاتها  pos : 1  neg : 0
word : غنايا  pos : 6  neg : 3
word : عالأغنية  pos : 1  neg : 0
word : شلكوها  pos : 0  neg : 1
word : جيب  pos : 11  neg : 133
word : حاط  pos : 0  neg : 7
word : راسينا  pos : 0  neg : 0
word : خير/  pos : 0  neg : 1
word : هلك  pos : 1  neg : 42
word : زاي  pos : 36  neg : 62
word : إعجاب  pos : 1  neg : 0
word : احترموا  pos : 0  neg : 0
word : ول  pos : 879  neg : 884
word : كمرة  pos : 1  neg : 0
word : تصدق  pos : 0  neg : 3
word : يعود  pos : 1  neg : 3
word : هبليهم  pos : 0  neg : 1
word : الكائن  pos : 0  neg : 2
word : بالبرتوقالي  pos : 0  neg : 0
word : أحسنيعجبني  pos : 1  neg : 0
word : عدك  pos : 8  neg : 17
word : يناقش  pos : 2  neg : 4
word : كلمه  pos : 1  neg : 2
word : مصطنعة  pos : 0  neg : 3
word : نتمسكو  pos : 0  neg : 0
word : يور  pos : 8  neg : 8
word : يدو  pos : 12  neg : 31
word : لحديث  pos : 2  neg : 3
word : ماعندكش  pos : 0  neg : 1
word : تمتعت  pos : 1  neg : 0
word : لحليب  pos : 0  neg : 4
word : لشعب  pos : 18  neg : 34
word : عالرخيص  pos : 0  neg : 1
word : مجاله  pos : 0  neg : 0
word : موفقة  pos : 2  neg : 0
word : تربحكم  pos : 0  neg : 18
word : مالحالات  pos : 1  neg : 0
word : والمعلم  pos : 2  neg : 0
word : إنت_معلم  pos : 1  neg : 0
word : التطور  pos : 0  neg : 1
word : مالبرنامج  pos : 0  neg : 0
word : اهانه  pos : 0  neg : 0
word : والكهوفلست  pos : 0  neg : 1
word : تحين  pos : 0  neg : 2
word : لشباب  pos : 2  neg : 6
word : رفعت  pos : 2  neg : 0
word : ولسان  pos : 0  neg : 2
word : ابلدهم  pos : 0  neg : 1
word : والتسيباله  pos : 0  neg : 1
word : الشايبة  pos : 0  neg : 1
word : الفيسة  pos : 0  neg : 1
word : القحب  pos : 0  neg : 24
word : فوح  pos : 2  neg : 0
word : كونفيونس  pos : 1  neg : 0
word : همجية  pos : 0  neg : 1
word : خدمتش  pos : 1  neg : 0
word : همل  pos : 5  neg : 15
word : يحق  pos : 1  neg : 5
word : فمو  pos : 3  neg : 3
word : غراب  pos : 0  neg : 4
word : ستد  pos : 1  neg : 16
word : سيدات  pos : 1  neg : 0
word : التفرقة  pos : 0  neg : 1
word : أكبرمنافق  pos : 0  neg : 0
word : تحط  pos : 3  neg : 8
word : صحافي  pos : 0  neg : 6
word : اتقو  pos : 6  neg : 9
word : الوظيفة  pos : 0  neg : 1
word : سيكون  pos : 0  neg : 1
word : العرب  pos : 6  neg : 14
word : متعاملش  pos : 0  neg : 1
word : ويبقى  pos : 0  neg : 0
word : الثوابت  pos : 0  neg : 1
word : اندمكم  pos : 0  neg : 1
word : إنضموا  pos : 0  neg : 1
word : وعلي  pos : 17  neg : 13
word : لابسته  pos : 0  neg : 0
word : أكون  pos : 0  neg : 0
word : مالمواطن  pos : 0  neg : 2
word : غسلو  pos : 0  neg : 3
word : شبعت  pos : 1  neg : 1
word : اقناع  pos : 1  neg : 0
word : والصحافين  pos : 0  neg : 1
word : حكة  pos : 23  neg : 6
word : مومثلة  pos : 0  neg : 0
word : حاد  pos : 2  neg : 2
word : يلوج  pos : 0  neg : 5
word : اشب  pos : 1  neg : 8
word : البلايد  pos : 0  neg : 1
word : لقاو  pos : 2  neg : 8
word : جيله  pos : 0  neg : 1
word : مثلت  pos : 2  neg : 5
word : اعلام_العار  pos : 0  neg : 2
word : مسوس  pos : 0  neg : 2
word : نهبط  pos : 0  neg : 1
word : صحة  pos : 157  neg : 3
word : إبني  pos : 0  neg : 1
word : العقربي  pos : 0  neg : 0
word : طيعتوا  pos : 1  neg : 0
word : تفجع  pos : 0  neg : 1
word : مالكذب  pos : 0  neg : 2
word : كثير  pos : 4  neg : 5
word : لدين  pos : 17  neg : 30
word : شيجيبوه  pos : 0  neg : 1
word : اعملوا  pos : 0  neg : 1
word : بوك  pos : 44  neg : 37
word : ديك  pos : 47  neg : 35
word : توفق  pos : 1  neg : 0
word : مسطولنا  pos : 0  neg : 1
word : تعملو  pos : 0  neg : 16
word : عالبروق  pos : 1  neg : 0
word : أنور  pos : 0  neg : 1
word : الديك)  pos : 0  neg : 1
word : القلوب  pos : 1  neg : 1
word : قلبها  pos : 4  neg : 2
word : الكاذبابحث  pos : 0  neg : 1
word : يقدر  pos : 5  neg : 2
word : التاريخوكذلك  pos : 0  neg : 1
word : احترمها  pos : 3  neg : 0
word : را  pos : 2887  neg : 1298
word : البراني  pos : 0  neg : 1
word : يصمت  pos : 0  neg : 1
word : وميع  pos : 0  neg : 1
word : لكلهم  pos : 2  neg : 5
word : بثه  pos : 0  neg : 0
word : موهرة  pos : 7  neg : 0
word : نوليو  pos : 0  neg : 1
word : بجانب  pos : 1  neg : 0
word : ايكو  pos : 1  neg : 0
word : مسخافة  pos : 0  neg : 1
word : اعلى  pos : 1  neg : 2
word : ملايكتوالشفاعة  pos : 0  neg : 2
word : الأحزاب  pos : 0  neg : 0
word : دبا  pos : 2  neg : 1
word : لجمهور  pos : 4  neg : 10
word : وناس  pos : 0  neg : 2
word : أزنافور  pos : 0  neg : 1
word : عصارة  pos : 0  neg : 0
word : تنهب  pos : 0  neg : 1
word : تفهم  pos : 2  neg : 7
word : مڨحفين  pos : 0  neg : 0
word : نزيد  pos : 1  neg : 2
word : شطيح  pos : 0  neg : 1
word : يستباندي  pos : 0  neg : 1
word : تعاسة  pos : 0  neg : 1
word : كريطة  pos : 0  neg : 0
word : إفهم  pos : 0  neg : 2
word : أخلاقيا  pos : 0  neg : 2
word : دودئ  pos : 1  neg : 0
word : تكلممتربية  pos : 0  neg : 0
word : يزبل  pos : 0  neg : 0
word : شدني  pos : 0  neg : 1
word : تضحك  pos : 11  neg : 18
word : باول  pos : 2  neg : 0
word : يقنع  pos : 2  neg : 0
word : نحبوك  pos : 31  neg : 0
word : خائبة  pos : 0  neg : 0
word : ياسي  pos : 38  neg : 28
word : وبطبيعة  pos : 0  neg : 1
word : أحن  pos : 8  neg : 4
word : محلاكم  pos : 50  neg : 0
word : منصف  pos : 0  neg : 3
word : برودة  pos : 1  neg : 1
word : ندافع  pos : 0  neg : 4
word : بأخلاقك  pos : 1  neg : 0
word : الفضح  pos : 0  neg : 6
word : نورشيبة  pos : 1  neg : 0
word : كفي  pos : 6  neg : 5
word : مشومة  pos : 0  neg : 2
word : الخايبة  pos : 0  neg : 1
word : والسفهاء  pos : 0  neg : 1
word : الشقاء  pos : 0  neg : 1
word : جملة  pos : 5  neg : 26
word : (3)  pos : 0  neg : 1
word : وظعك  pos : 0  neg : 1
word : تكلم  pos : 20  neg : 35
word : وميبون  pos : 0  neg : 2
word : كاكا  pos : 1  neg : 9
word : تعلمون"  pos : 0  neg : 1
word : صون  pos : 4  neg : 1
word : سانسيرمون  pos : 1  neg : 0
word : الحسرا  pos : 0  neg : 1
word : زيتونة  pos : 0  neg : 1
word : والمزيد  pos : 0  neg : 0
word : العرس  pos : 0  neg : 3
word : اعماق  pos : 1  neg : 0
word : الشهور  pos : 0  neg : 0
word : يغسلوش  pos : 0  neg : 1
word : اتهين  pos : 0  neg : 1
word : يمصاط  pos : 0  neg : 1
word : راسهم  pos : 2  neg : 0
word : لأنه  pos : 1  neg : 3
word : مفتاحي  pos : 2  neg : 0
word : بالفعل  pos : 3  neg : 0
word : نسب  pos : 18  neg : 16
word : اعتزل  pos : 0  neg : 1
word : حكان  pos : 0  neg : 0
word : وفقكم  pos : 4  neg : 0
word : مكتملة  pos : 1  neg : 0
word : فالفلاحة  pos : 0  neg : 1
word : وبنتي  pos : 1  neg : 0
word : هقارة  pos : 0  neg : 1
word : البت  pos : 1  neg : 1
word : ثلاثة  pos : 0  neg : 2
word : ايجا  pos : 2  neg : 3
word : إستءذان  pos : 1  neg : 0
word : الباسل  pos : 0  neg : 1
word : يقلها  pos : 1  neg : 1
word : وبءس  pos : 0  neg : 2
word : كافيةمرسي  pos : 1  neg : 0
word : وزمباوي  pos : 0  neg : 1
word : الحوارات  pos : 0  neg : 2
word : كالشوكة  pos : 0  neg : 1
word : ماتضحكش  pos : 0  neg : 3
word : بتفدليك  pos : 0  neg : 0
word : حناك  pos : 0  neg : 4
word : هو:قناة  pos : 0  neg : 0
word : لفضيل  pos : 0  neg : 8
word : أمنيتي  pos : 2  neg : 0
word : بريف  pos : 0  neg : 0
word : غالطين  pos : 0  neg : 2
word : يتبعو  pos : 0  neg : 1
word : صوابع  pos : 0  neg : 3
word : نشرب  pos : 0  neg : 1
word : الحانات  pos : 0  neg : 1
word : يزيدني  pos : 1  neg : 0
word : الاطراء  pos : 0  neg : 1
word : مايتهضمش  pos : 0  neg : 1
word : فيهوش  pos : 0  neg : 2
word : حيام  pos : 0  neg : 1
word : قنفود  pos : 1  neg : 2
word : نقعوه  pos : 0  neg : 0
word : الإهتمام  pos : 0  neg : 0
word : الفضائي  pos : 0  neg : 1
word : حبوب  pos : 17  neg : 4
word : شويات  pos : 2  neg : 1
word : وماشي  pos : 0  neg : 0
word : ريسبي  pos : 1  neg : 1
word : يشفيك  pos : 9  neg : 0
word : طايارة  pos : 2  neg : 0
word : يسافر  pos : 1  neg : 0
word : أهل  pos : 3  neg : 5
word : يمثلوها  pos : 0  neg : 1
word : ميعمل  pos : 0  neg : 0
word : رواحكم  pos : 0  neg : 4
word : الكميديا  pos : 1  neg : 0
word : تذكرنى  pos : 1  neg : 0
word : يجيش  pos : 0  neg : 11
word : أي  pos : 18  neg : 34
word : ماريت  pos : 0  neg : 10
word : يمرض  pos : 0  neg : 3
word : محلك  pos : 7  neg : 0
word : زلاوجة  pos : 0  neg : 1
word : خوفني  pos : 0  neg : 0
word : أضعف  pos : 0  neg : 1
word : نايك  pos : 0  neg : 9
word : باعراض  pos : 0  neg : 1
word : رامز  pos : 1  neg : 1
word : لوغتها  pos : 1  neg : 0
word : السد  pos : 0  neg : 1
word : المايع  pos : 0  neg : 1
word : مدفون  pos : 0  neg : 1
word : ويتفرج  pos : 0  neg : 2
word : تجارب  pos : 0  neg : 1
word : رخصت  pos : 0  neg : 1
word : يتبكى  pos : 0  neg : 1
word : العابدين  pos : 0  neg : 1
word : خبيثة  pos : 0  neg : 1
word : عالساحة  pos : 1  neg : 0
word : باري  pos : 0  neg : 4
word : بحذ  pos : 3  neg : 1
word : الناتن  pos : 0  neg : 2
word : مابلدها  pos : 0  neg : 3
word : سنين  pos : 2  neg : 6
word : "حالي  pos : 0  neg : 1
word : مرفوضة  pos : 0  neg : 1
word : فلا  pos : 1  neg : 9
word : إمام  pos : 0  neg : 2
word : الشلالة  pos : 0  neg : 1
word : يأتي  pos : 1  neg : 2
word : يقال  pos : 0  neg : 1
word : ياشيخ  pos : 0  neg : 2
word : الاول  pos : 10  neg : 1
word : حاميها  pos : 0  neg : 1
word : عظيمةبرافو  pos : 1  neg : 0
word : دبة  pos : 0  neg : 1
word : شاحطه  pos : 0  neg : 2
word : مقولة  pos : 1  neg : 0
word : '  pos : 12  neg : 15
word : بره  pos : 22  neg : 9
word : تعملهم  pos : 1  neg : 0
word : وزقرتولها  pos : 0  neg : 1
word : السحاقيات  pos : 0  neg : 1
word : لامفر  pos : 0  neg : 1
word : وخصها  pos : 1  neg : 0
word : تسطتيعي  pos : 0  neg : 1
word : اتوب  pos : 0  neg : 1
word : مجالها  pos : 0  neg : 0
word : عمدة  pos : 1  neg : 1
word : وجب  pos : 0  neg : 6
word : الأم  pos : 6  neg : 18
word : نورمالمون  pos : 1  neg : 4
word : جايبينها  pos : 0  neg : 4
word : باقبح  pos : 0  neg : 1
word : يحكينرقد  pos : 0  neg : 1
word : العمارى  pos : 0  neg : 1
word : والطاقم  pos : 0  neg : 0
word : عطيتها  pos : 2  neg : 0
word : أعزو  pos : 1  neg : 0
word : خذاه  pos : 1  neg : 1
word : قطاع  pos : 1  neg : 0
word : ماتحشميش  pos : 0  neg : 1
word : تجربوش  pos : 0  neg : 1
word : جابة  pos : 3  neg : 1
word : ماهضمتوش  pos : 0  neg : 2
word : واحلى  pos : 3  neg : 0
word : مصدق  pos : 1  neg : 1
word : موتك  pos : 0  neg : 1
word : التقنين  pos : 0  neg : 1
word : شام  pos : 13  neg : 9
word : العرايف  pos : 1  neg : 0
word : تجسد  pos : 0  neg : 0
word : واطية  pos : 0  neg : 1
word : يقلي  pos : 0  neg : 2
word : طلبا  pos : 0  neg : 2
word : ماتحياش  pos : 0  neg : 1
word : ضهرلك  pos : 1  neg : 0
word : ماتفهكم  pos : 0  neg : 1
word : ماشا  pos : 136  neg : 2
word : فيق  pos : 61  neg : 74
word : حبا  pos : 11  neg : 5
word : متحضر  pos : 2  neg : 0
word : ومرمزو  pos : 0  neg : 1
word : اغني  pos : 1  neg : 4
word : وزرع  pos : 0  neg : 1
word : بوق  pos : 6  neg : 2
word : ردي  pos : 4  neg : 18
word : انجاح  pos : 1  neg : 0
word : ذريعة  pos : 0  neg : 1
word : واقعية  pos : 3  neg : 0
word : لعماري  pos : 3  neg : 26
word : رزان  pos : 8  neg : 1
word : داعشي  pos : 0  neg : 4
word : وعمي  pos : 1  neg : 1
word : ربحكم  pos : 0  neg : 21
word : ميز  pos : 16  neg : 1
word : كروان  pos : 1  neg : 0
word : جعفرانت  pos : 0  neg : 0
word : الموهوبات  pos : 1  neg : 0
word : باشا  pos : 4  neg : 0
word : جوهم  pos : 1  neg : 4
word : يطرد  pos : 0  neg : 1
word : مواهر  pos : 12  neg : 0
word : عالفن  pos : 0  neg : 1
word : يعرفهم  pos : 0  neg : 1
word : تقريب  pos : 0  neg : 0
word : يدوره  pos : 0  neg : 0
word : وبرا  pos : 5  neg : 0
word : سملة  pos : 0  neg : 0
word : الحواري  pos : 1  neg : 0
word : شرف  pos : 43  neg : 46
word : ساهلة  pos : 1  neg : 0
word : نضرب  pos : 0  neg : 0
word : وخفة  pos : 1  neg : 0
word : بالفم  pos : 2  neg : 0
word : عحبتني  pos : 1  neg : 0
word : العمران  pos : 1  neg : 0
word : ايديولجية  pos : 0  neg : 1
word : منافقة  pos : 0  neg : 3
word : لقصة  pos : 1  neg : 1
word : برافا  pos : 1  neg : 0
word : نجيبك  pos : 1  neg : 0
word : الباشا  pos : 0  neg : 0
word : لاشئ  pos : 0  neg : 1
word : العريف  pos : 0  neg : 2
word : القادر  pos : 1  neg : 0
word : ضواه  pos : 1  neg : 0
word : مستوصف  pos : 0  neg : 1
word : لعضيم  pos : 0  neg : 0
word : حفة  pos : 11  neg : 0
word : شمل  pos : 6  neg : 0
word : بعدو  pos : 1  neg : 3
word : مخها  pos : 1  neg : 2
word : اتغطسهم  pos : 1  neg : 0
word : ماتقل  pos : 0  neg : 1
word : محليها  pos : 11  neg : 0
word : طلاقة  pos : 1  neg : 0
word : يقلد  pos : 0  neg : 2
word : محلها  pos : 4  neg : 1
word : هي  pos : 188  neg : 299
word : يقولالشيب  pos : 0  neg : 1
word : ماتجيبو  pos : 0  neg : 4
word : تدخلات  pos : 2  neg : 1
word : بلدكم  pos : 0  neg : 4
word : ولابس  pos : 0  neg : 1
word : يسترنا  pos : 3  neg : 4
word : فحصتك  pos : 1  neg : 0
word : وحصة  pos : 1  neg : 0
word : البيسكلات  pos : 0  neg : 1
word : البصري  pos : 0  neg : 0
word : مد  pos : 103  neg : 103
word : اكبري  pos : 0  neg : 0
word : الخير  pos : 26  neg : 2
word : نركح  pos : 0  neg : 1
word : مضروبة  pos : 0  neg : 5
word : أنتيكة  pos : 1  neg : 0
word : توه  pos : 5  neg : 37
word : تشرفوش  pos : 0  neg : 4
word : يصبغ  pos : 0  neg : 1
word : آناقة  pos : 3  neg : 0
word : اتحسها  pos : 1  neg : 0
word : ايديك  pos : 1  neg : 0
word : يونسي  pos : 1  neg : 0
word : مالكوارث  pos : 0  neg : 1
word : ايكب  pos : 0  neg : 1
word : فاماش  pos : 1  neg : 1
word : مضجر  pos : 0  neg : 1
word : سطوفة  pos : 3  neg : 0
word : العرش  pos : 0  neg : 2
word : يمثل  pos : 6  neg : 15
word : فما  pos : 24  neg : 52
word : ويلوج  pos : 0  neg : 1
word : ركب  pos : 0  neg : 16
word : مفعول  pos : 0  neg : 1
word : المناظر  pos : 0  neg : 12
word : تغلات  pos : 0  neg : 1
word : التلفغزة  pos : 0  neg : 1
word : الناس"  pos : 1  neg : 0
word : ومريض  pos : 0  neg : 4
word : حظها  pos : 1  neg : 0
word : بجواب  pos : 1  neg : 0
word : تعرفني  pos : 0  neg : 1
word : عسو  pos : 39  neg : 4
word : زينيك  pos : 1  neg : 0
word : مراة  pos : 12  neg : 4
word : بهامة  pos : 0  neg : 10
word : يقتدين  pos : 1  neg : 0
word : ياكريم  pos : 1  neg : 0
word : هيبتها  pos : 0  neg : 0
word : اغنية  pos : 0  neg : 3
word : يابنت  pos : 0  neg : 1
word : ذنوب  pos : 0  neg : 2
word : حيحون  pos : 0  neg : 2
word : غشت  pos : 0  neg : 1
word : العي  pos : 17  neg : 113
word : وطلع  pos : 0  neg : 0
word : سامى  pos : 2  neg : 1
word : مصطكين  pos : 1  neg : 0
word : روحها  pos : 28  neg : 42
word : اندلسي  pos : 11  neg : 11
word : نحكيو  pos : 0  neg : 1
word : ونتشرفو  pos : 1  neg : 0
word : زنديق  pos : 0  neg : 8
word : هبلهم  pos : 9  neg : 1
word : التيليفزيون  pos : 1  neg : 0
word : الرئاسية  pos : 1  neg : 0
word : وتستحق  pos : 2  neg : 0
word : النوم  pos : 1  neg : 0
word : متالقة  pos : 9  neg : 0
word : واليمن  pos : 0  neg : 1
word : اعملتو  pos : 0  neg : 1
word : النقص  pos : 0  neg : 2
word : الفحش  pos : 0  neg : 3
word : اندو  pos : 0  neg : 1

In [ ]:
train_data = train_data.reset_index(drop=True)
test_data = test_data.reset_index(drop=True)

In [ ]:
#building the trainiig dataset
matrix_df_train = np.zeros((len(train_data),3))
for i ,row in train_data.iterrows():

  matrix_df_train[i,2] = row['label']
  for w in row['tokinized_text']:
    pos,neg = word2freq(w)
    matrix_df_train[i,0] += pos
    matrix_df_train[i,1] += neg

In [ ]:
df_train = pd.DataFrame(matrix_df_train,columns = ['positive_count' , 'negative_count',"label"])

In [ ]:
df_train

       positive_count  negative_count  label
0              7184.0          9391.0    0.0
1             12771.0         13625.0    1.0
2              1142.0          2955.0    0.0
3               164.0             1.0    1.0
4              2237.0          1457.0    1.0
...               ...             ...    ...
13638          1836.0          1265.0    1.0
13639             2.0           290.0    0.0
13640         30685.0         33158.0    1.0
13641           829.0            23.0    1.0
13642          1728.0          2121.0    0.0

[13643 rows x 3 columns]

In [ ]:
#building the trainiig dataset
matrix_df_test = np.zeros((len(test_data),3))
for i ,row in test_data.iterrows():

  matrix_df_test[i,2] = row['label']
  for w in row['tokinized_text']:
    pos,neg = word2freq(w)
    matrix_df_test[i,0] += pos
    matrix_df_test[i,1] += neg

In [ ]:
df_test = pd.DataFrame(matrix_df_test,columns = ['positive_count' , 'negative_count',"label"])

In [ ]:
df_train

       positive_count  negative_count  label
0              7184.0          9391.0    0.0
1             12771.0         13625.0    1.0
2              1142.0          2955.0    0.0
3               164.0             1.0    1.0
4              2237.0          1457.0    1.0
...               ...             ...    ...
13638          1836.0          1265.0    1.0
13639             2.0           290.0    0.0
13640         30685.0         33158.0    1.0
13641           829.0            23.0    1.0
13642          1728.0          2121.0    0.0

[13643 rows x 3 columns]

In [ ]:
X_train= df_train.drop('label',axis=1).to_numpy()
Y_train = df_train['label'].to_numpy()

X_test = df_test.drop('label',axis=1).to_numpy()
Y_test = df_test['label'].to_numpy()

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

y_pred = log_reg.fit(X_train, Y_train).predict(X_test)
accuracy = log_reg.score(X_test, Y_test)

In [ ]:
print(f"accuracy : {accuracy:.4f}")

accuracy : 0.7282

In [ ]:
def inference(text):
  #i need to make the preprocessing a function
  tokinized_text = tokenize(text)
  positive_counts = 0
  negative_counts =0

  for w in tokinized_text:
    pos,neg = word2freq(w)
    positive_counts += pos
    negative_counts += neg

  features = np.array([[positive_counts,negative_counts]])
  return f"log_reg.predict(features)[0].item()"

In [ ]:
GREEN = "\033[92m"
RED = "\033[91m"
CYAN = "\033[96m"
YELLOW = "\033[93m"
RESET = "\033[0m"

for i, row in test_data.iterrows():

    text = row["text"]
    actual_label = row["label"]
    pred_label = inference(text)

    color = GREEN if actual_label == pred_label else RED
    status = "✓ CORRECT" if actual_label == pred_label else "✗ WRONG"

    print(f"{CYAN}Text:{RESET} {text}")
    print(f"{YELLOW}Actual label:{RESET} {actual_label}")
    print(f"{CYAN}Predicted label:{RESET} {pred_label}")
    print(f"{color}{status}{RESET}")
    print("-" * 80)

Streaming output truncated to the last 5000 lines.
Text: فلو
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: الشكسرة والبحر
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مصطها اليلة ماقر شكيب
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: عبيطة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: عيب عليك الناس تفرج في ديارهم عائلة معاهم بنات عيب عليك أنتي راجل كبير و ناس الكل كانت تقدرك أي كانت خاطر بعد الحلقة باش توالي تفريكة 2016
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مابسلو عبد توا هذا يضحك بجاه ربي
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ماسط عالآخر
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسط
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مريض و متخلف و ماقل حياه قداش ماهوش متربي
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: اوه مصطيك امشي ارقد
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ملهط
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ماتعجبنيش بصراحة مارقة برشا تعملي جاير اف
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: يهبل
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: امصط مغني شافتوا وذني وسمعتوا عيني
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مخيب جلغتك زعام كان في تمقعير
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ملا فضايح
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ه هرتها مرض و نعرف دواه ربي إي أنفان يا مقداد
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: وينو راس البسلة ه
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسطة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: الشيب و العيب
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ياسر ثقيل وماسط وبلاسطو في الراديو
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: يا خويا أمسط منك ما راتش عيني
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: توفيق الغربي نوع من الارهاب السمعي و البصري والمعنوي بالنسبه ليا خيبيبت
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ياسر ماسط من محمد علي النهدي لمحمد الجبالي وبندرمان ربي يخف علينا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: حيوان ا لوس
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: فاشل
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: قحبة كبيرة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: أشبيه ماسط هاكا إيقول لشكيب نهضاوي علاه ما يسألش لعماري أشبيه من النداء
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: رمز الفشل
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: هي و توفيق طنجرة و لقات غطاها في المساطة شي يعيف
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مخيب وجه
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ملعون أبوك يا فقر يا محوجني لأنذال ذليت عزيز النفس عشان عديم المال ملعون أبوك يا عوزة ذلت السؤال قتال آه لو لعبت يا زهر و تبدلت الآحوال و ركبت أول موجة في سكة الآموال لروح لأول واحد إحتجتلو في سؤال كسر بخطري ساعتها و ذوقني ضيق الحال لعمل معاه الصح أنا و أسندو لو مال و أقف جنبو فالمحن و أكون طويل البال و أعلمو الفلوس متصنعش رجال و الحوجة مرة ياما بهزلت أبطال
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: يزي من التنوفيق متع النهضاويةمرمد لطحانة و الشعب معاك
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: سلعة قزاز
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: قلة تربية
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: قداه نكره
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: حيونات يراهم مشلولين
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: تفو عل المستويات المنحطة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: انسان جاهل  :(
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: كل مرة تزيد تسقط من عينينا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: شكيب مصطك يا راجل ظاهر يا بابا يامي يزيك من التنوفيق
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: واله زايد خامج و ماسخ و ماتواليش عبد باله أمك و أختك تفرجو فاها القطة هاذيكا
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: المهم ثمة رهوط حاشا خلقة الرحمن ماعاش نحبو نشوفوها 'في لباس'
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ياخي مش قاعد يشوف في خليتو في المراية هالكارثة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مخمجه
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ماعجبنيش
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: هذا البرنامج اهانه لكل تونسى  اخوكم من ليبيا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: اتفه انسانة ريتها و تقول مثلة منين جك الموهبة تفها و ساخيفة ت حمقاء و زيد عفشة و متصلحش فنانة تمشي تحل كيما قلت هي حانوت كسكروتات موش تعلمت كلمتن بسوري ولات تعطي في حقوق لانسان تف تف تف تف عليها و علي  ملا حالة في تونس
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: اله يهديكم جايبين شبه مثلة تعطي في رايها تمعجن في الكلام حاسة روحها اش من حاجة اف تقز
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text:  شكيب يوتر الأعصاب مقلق مقلق مقلق مقلق يفد فدة غمة على القلب
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: تعيف
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مخيب راسو
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: كلاش فاشل
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: عفط
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مشى منيك جا انيك
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: طحان كبير
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مرا بألف طحان من الجهال الي يسبوا فيها
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مصط والدين أمو منين جايبينو هالخرا لكزة هذا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسطة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: واحد من البندارة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: يا توفيق انك تكره تيار معين لا يعني أن ترفض التحاور مع الناس و الضيوف أنت هكذا تثبت ضعفك
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: وجوه يوما إذن
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ماسط
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: حمار مسطو عبد ومركو واله يستاهل كفوف
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: شي اسف واله
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: تفوه عليك
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: نوفل الورتاني ماعادش تكتب  الحلقة الاولى فاشلة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: عزوز جايتها في عقاب عمرها
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: تفوه عليك يا بيوع
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: يخوف سخطة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مصطيها
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: سبحان اله شعب راضع طحين شعب يموت على القمع ه بربي عطوني سب واحد يخليكم تسبو النهضة علاش ما تسبوش الأحزاب لي متسمية على التجمع
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: باية أنا ماتعجبنيش و مانيش عارف شبيها ضربة ضربتين تريكل بروبيتها ربي يصبر علينا لع قال
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: يحكي على التربية و هو موش متربي
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: حشاكم خرية وريحتو خرجت مالتفزة  هو مش محترم ومش متربي ويحكي عالتربية كينو الوحيد في تونس متربي  وهو بالعكس الوحيد مش متربي في تونس هو مقداد السهيلي
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: شبيها ديما مخها خامج و ماشي كان لفساد بف
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: كلب يهودي طحان قواد تفوه عليه
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: برا اله يلعن بوك وبو أمك العاهرة يا سامي الفهري يا طحان ماكش راجل بايع شرفك يا عديم الأصل يا ديوث تفوه عليك وعلى الطحانة الي تبع فيك
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: محلاها
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ملا منظر أحرف خيط عالصباح تقعد ماخيبك :/
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماهوش متربي و بهيم
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: راك ماسط راك لاسط راك سلعة متشيخش جملةصاحبي موكش متع فكاهة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسطة
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: اتفوه على اولاد الرقاصة والي يتفرج فيهم
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسط برشا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: الي كيفو لازم يموتو
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مرق و مسط
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مريض واله
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مارق
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: كريوك خنث تافه طحان ماسط جبري فاشل لكز عفش رهط فاسد متخلف مريض
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماخيبهم
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: لا فيكم واحد ينفع كان الكذب و النفاق
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: اوه مسطو وكان مشي عمل حاجة اخرى خير
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ملا مجانين وسامي معاهم
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسطة بارشا :(
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: تعيف
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مش تسخف تزعبن
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: لاعبتها قافزة و تشنفخ راك مجيت شي و كيما قال كافون راك ماست راك لاسط شكون انت باش تحكي على احمد الاندلسي غير توصلو
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: مسقتها إيناس ومعجبتنيش الحلقه
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مكانش امصط منكم يا مصطا
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: رزين
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مصطها
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: تفيه عليك
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ياسر قلة حيا عايلات تفرج راو سلت
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: قحبة
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: أحمد الأندلسي سيدك يا نكرةاشكونك إنت يا ماسطةيا فرحة الراجل إلي باش ياخذك وفرحة بوكوهف يهزك
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ربي يشفيه
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: حالتو متعبه أصل
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: سبحان اله ملا مناظر
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مصطهم ملا امارك مقلبة -_-
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسط برشا
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: تفو على هالمناظر
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ماسط لاسط لعبها مبدع وهو ابداعو الوحيد الطحين والسراب وعداء لنهضة اكب سعدك النهضة لا تمنى ان يناصرها امثالك يا منحط
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ملا حالة ملا غناية ف
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: انسانه ماتعجبنش
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: وانا نقول شبيه مسطو  ملا لحاس  يعطيع عصا على راسو مسطو براس امكم طردوه  خايب
Actual label: 0
Predicted label: 0.0
✓ CORRECT
--------------------------------------------------------------------------------
Text: ميرق
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: مصطها ومخيبها وهي اصلا شكونهي
Actual label: 0
Predicted label: 1.0
✗ WRONG
--------------------------------------------------------------------------------
Text: ما عجبتنيش علاه أونو حقيقة